# Generated by Django 5.0.7 on 2024-07-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task",
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
