# Generated by Django 5.0.7 on 2024-07-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="notification_interval",
            field=models.CharField(
                blank=True,
                choices=[("hour", "Hourly"), ("day", "Daily")],
                max_length=50,
                null=True,
            ),
        ),
    ]
