# Generated by Django 5.0.7 on 2024-07-16 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_notification_interval"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="telegram_nick",
            new_name="email",
        ),
    ]
